# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 677)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icon/icons/icon_128.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setIconSize(QtCore.QSize(128, 128))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageQueryEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imageQueryEdit.sizePolicy().hasHeightForWidth()
        )
        self.imageQueryEdit.setSizePolicy(sizePolicy)
        self.imageQueryEdit.setText("")
        self.imageQueryEdit.setObjectName("imageQueryEdit")
        self.horizontalLayout.addWidget(self.imageQueryEdit)
        self.getWallpaperButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.getWallpaperButton.sizePolicy().hasHeightForWidth()
        )
        self.getWallpaperButton.setSizePolicy(sizePolicy)
        self.getWallpaperButton.setMinimumSize(QtCore.QSize(0, 36))
        self.getWallpaperButton.setObjectName("getWallpaperButton")
        self.horizontalLayout.addWidget(self.getWallpaperButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.APIComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.APIComboBox.setObjectName("APIComboBox")
        self.APIComboBox.addItem("")
        self.APIComboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.APIComboBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.imageOrientationComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.imageOrientationComboBox.setObjectName("imageOrientationComboBox")
        self.imageOrientationComboBox.addItem("")
        self.imageOrientationComboBox.addItem("")
        self.imageOrientationComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.imageOrientationComboBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.purityLayout = QtWidgets.QHBoxLayout()
        self.purityLayout.setObjectName("purityLayout")
        self.SFWCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.SFWCheckBox.setObjectName("SFWCheckBox")
        self.purityLayout.addWidget(self.SFWCheckBox)
        self.SketchyCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.SketchyCheckBox.setObjectName("SketchyCheckBox")
        self.purityLayout.addWidget(self.SketchyCheckBox)
        self.NSFWCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.NSFWCheckBox.setObjectName("NSFWCheckBox")
        self.purityLayout.addWidget(self.NSFWCheckBox)
        self.horizontalLayout_10.addLayout(self.purityLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageArea = QtWidgets.QGraphicsView(parent=self.tab)
        self.imageArea.setViewportUpdateMode(
            QtWidgets.QGraphicsView.ViewportUpdateMode.FullViewportUpdate
        )
        self.imageArea.setObjectName("imageArea")
        self.verticalLayout.addWidget(self.imageArea)
        self.creditsLabel = QtWidgets.QLabel(parent=self.tab)
        self.creditsLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.creditsLabel.setOpenExternalLinks(True)
        self.creditsLabel.setObjectName("creditsLabel")
        self.verticalLayout.addWidget(self.creditsLabel)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 931, 442))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.downloadDirectoryEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.downloadDirectoryEdit.setObjectName("downloadDirectoryEdit")
        self.horizontalLayout_6.addWidget(self.downloadDirectoryEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.wallpaperCommandEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.wallpaperCommandEdit.setObjectName("wallpaperCommandEdit")
        self.horizontalLayout_4.addWidget(self.wallpaperCommandEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.apiTokenEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiTokenEdit.sizePolicy().hasHeightForWidth())
        self.apiTokenEdit.setSizePolicy(sizePolicy)
        self.apiTokenEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.apiTokenEdit.setObjectName("apiTokenEdit")
        self.horizontalLayout_3.addWidget(self.apiTokenEdit)
        self.showAPITokenButton = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.showAPITokenButton.sizePolicy().hasHeightForWidth()
        )
        self.showAPITokenButton.setSizePolicy(sizePolicy)
        self.showAPITokenButton.setObjectName("showAPITokenButton")
        self.horizontalLayout_3.addWidget(self.showAPITokenButton)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.resetSettingsButton = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.resetSettingsButton.sizePolicy().hasHeightForWidth()
        )
        self.resetSettingsButton.setSizePolicy(sizePolicy)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.horizontalLayout_2.addWidget(self.resetSettingsButton)
        self.applySettingsButton = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.applySettingsButton.sizePolicy().hasHeightForWidth()
        )
        self.applySettingsButton.setSizePolicy(sizePolicy)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.horizontalLayout_2.addWidget(self.applySettingsButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.setWallpaperButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.setWallpaperButton.sizePolicy().hasHeightForWidth()
        )
        self.setWallpaperButton.setSizePolicy(sizePolicy)
        self.setWallpaperButton.setMinimumSize(QtCore.QSize(0, 36))
        self.setWallpaperButton.setObjectName("setWallpaperButton")
        self.verticalLayout_2.addWidget(self.setWallpaperButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WallpaperED"))
        self.imageQueryEdit.setPlaceholderText(
            _translate("MainWindow", "flowers, people, color, etc..")
        )
        self.getWallpaperButton.setToolTip(_translate("MainWindow", "Enter"))
        self.getWallpaperButton.setText(_translate("MainWindow", "Get Wallpaper!"))
        self.getWallpaperButton.setShortcut(_translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "Image Provider"))
        self.APIComboBox.setItemText(0, _translate("MainWindow", "unsplash"))
        self.APIComboBox.setItemText(1, _translate("MainWindow", "wallhaven"))
        self.label_6.setText(_translate("MainWindow", "Image Orientation"))
        self.imageOrientationComboBox.setItemText(
            0, _translate("MainWindow", "landscape")
        )
        self.imageOrientationComboBox.setItemText(
            1, _translate("MainWindow", "squarish")
        )
        self.imageOrientationComboBox.setItemText(
            2, _translate("MainWindow", "portrait")
        )
        self.SFWCheckBox.setText(_translate("MainWindow", "SFW"))
        self.SketchyCheckBox.setText(_translate("MainWindow", "Sketchy"))
        self.NSFWCheckBox.setText(_translate("MainWindow", "NSFW"))
        self.creditsLabel.setText(_translate("MainWindow", "Captured by"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Application Settings"))
        self.label_3.setText(_translate("MainWindow", "Download directory"))
        self.downloadDirectoryEdit.setPlaceholderText(
            _translate("MainWindow", "~/path/to/dowbload/direcory")
        )
        self.label_5.setText(_translate("MainWindow", "Commands to update wallpaper"))
        self.wallpaperCommandEdit.setPlaceholderText(
            _translate("MainWindow", "Use %PATH% to specify your download directory...")
        )
        self.label.setText(_translate("MainWindow", "*commands separated by new line"))
        self.label_4.setText(_translate("MainWindow", "API Token"))
        self.apiTokenEdit.setPlaceholderText(_translate("MainWindow", "API-TOKEN"))
        self.showAPITokenButton.setText(_translate("MainWindow", "Show"))
        self.showAPITokenButton.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.resetSettingsButton.setText(_translate("MainWindow", "Reset"))
        self.resetSettingsButton.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.applySettingsButton.setText(_translate("MainWindow", "Apply"))
        self.applySettingsButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings")
        )
        self.setWallpaperButton.setToolTip(_translate("MainWindow", "Ctrl+Alt+Enter"))
        self.setWallpaperButton.setText(_translate("MainWindow", "Set Wallpaper!"))
        self.setWallpaperButton.setShortcut(_translate("MainWindow", "Ctrl+Alt+Return"))
